openapi: '3.0.0'
info:
  title: LogRhythm Case API
  version: '3.0.0'
  description: This is the API documentation for the LogRhythm Case service.
servers:
  - url: https://localhost:8501/lr-case-api
    description: Local API Gateway (https)
paths:
  '/cases':
    get:
      operationId: listCases
      summary: List Cases
      description: Retrieve a filtered list of cases. Supports pagination.
      parameters:
        - name: offset
          in: query
          description: Where to start paging
          required: false
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: The returned case.
          content:
            'application/vnd.logrhythm.case.list.v1+json':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CaseV1'
            'application/vnd.logrhythm.case.list.v2+json':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CaseV2'
  '/cases/{id}':
    put:
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the Case to add evidence to.
          schema:
            type: string
            format: uuid
      operationId: updateCase
      requestBody:
        content:
          'application/vnd.logrhythm.case.v1+json':
            schema:
              required:
                - name
              allOf:
                - $ref: '#/components/schemas/CaseEditableFieldsV1'
          'application/vnd.logrhythm.case.v2+json':
            schema:
              required:
                - name
                - status
              allOf:
                - $ref: '#/components/schemas/CaseEditableFieldsV2'
      responses:
        '200':
          description: The updated case.
          content:
            'application/vnd.logrhythm.case.list.v1+json':
              schema:
                $ref: '#/components/schemas/CaseV1'
            'application/vnd.logrhythm.case.list.v2+json':
              schema:
                $ref: '#/components/schemas/CaseV2'
    patch:
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the Case to add evidence to.
          schema:
            type: string
            format: uuid
      operationId: patchCase
      requestBody:
        content:
          'application/vnd.logrhythm.case.v1.merge-patch+json':
            schema:
              allOf:
                - $ref: '#/components/schemas/CaseEditableFieldsV1'
          'application/vnd.logrhythm.case.v2.merge-patch+json':
            schema:
              allOf:
                - $ref: '#/components/schemas/CaseEditableFieldsV2'
      responses:
        '200':
          $ref: '#/components/responses/UpdatedCaseAllVersions'
          # description: The updated case.
          # content:
          #   'application/vnd.logrhythm.case.list.v1+json':
          #     schema:
          #       $ref: '#/components/schemas/CaseV1'
          #   'application/vnd.logrhythm.case.list.v2+json':
          #     schema:
          #       $ref: '#/components/schemas/CaseV2'
  '/cases/{id}/evidence':
    post:
      operationId: createEvidence
      summary: Create Evidence
      description: Add a new piece of evidence to a case.
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the Case to add evidence to.
          schema:
            type: string
            format: uuid
      requestBody:
        content:
          'application/vnd.logrhythm.case-evidence.list.v1+json':
            schema:
              type: array
              items:
                type: object
                oneOf:
                  - $ref: '#/components/schemas/NoteEvidence'
                  - $ref: '#/components/schemas/AlarmEvidence'
                discriminator:
                  propertyName: evidenceType
      responses:
        '201':
          description: The created evidence
          content:
            'application/vnd.logrhythm.case-evidence.list.v1+json':
              schema:
                type: array
                items:
                  type: object
                  oneOf:
                    - $ref: '#/components/schemas/NoteEvidence'
                    - $ref: '#/components/schemas/AlarmEvidence'
                  discriminator:
                    propertyName: evidenceType

components:
  schemas:
    CaseEditableFieldsV1:
      type: object
      properties:
        name:
          type: string
    CaseEditableFieldsV2:
      type: object
      allOf:
        - $ref: '#/components/schemas/CaseEditableFieldsV1'
        - type: object
          properties:
            status:
              type: integer
              format: int32
              minimum: 1
              maximum: 5
    CaseDerivedFields:
      type: object
      properties:
        id:
          type: string
          format: uuid
        createdBy:
          $ref: '#/components/schemas/Person'
        lastUpdatedBy:
          $ref: '#/components/schemas/Person'
    CaseV1:
      type: object
      required:
        - id
        - name
      allOf:
        - $ref: '#/components/schemas/CaseDerivedFields'
        - $ref: '#/components/schemas/CaseEditableFieldsV1'
    CaseV2:
      type: object
      required:
        - id
        - name
        - status
      allOf:
        - $ref: '#/components/schemas/CaseDerivedFields'
        - $ref: '#/components/schemas/CaseEditableFieldsV2'
    Evidence:
      type: object
      discriminator:
        propertyName: evidenceType
      required:
        - id
        - evidenceType
      properties:
        id:
          type: integer
          format: int32
        evidenceType:
          type: string
        createdBy:
          $ref: '#/components/schemas/Person'
    NoteEvidence:
      allOf:
        - $ref: '#/components/schemas/Evidence'
        - type: object
          required:
            - note
          properties:
            note:
              type: string
    AlarmEvidence:
      allOf:
        - $ref: '#/components/schemas/Evidence'
        - type: object
          required:
            - alarmId
          properties:
            alarmId:
              type: integer
              format: int32
    Person:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
  responses:
    UpdatedCaseAllVersions:
      description: The updated case.
      content:
        'application/vnd.logrhythm.case.list.v1+json':
          schema:
            $ref: '#/components/schemas/CaseV1'
        'application/vnd.logrhythm.case.list.v2+json':
          schema:
            $ref: '#/components/schemas/CaseV2'
