openapi: '3.0.0'
info:
  title: LogRhythm Case API
  version: '3.0.0'
  description: This is the API documentation for the LogRhythm Case service.
servers:
  - url: https://localhost:8501/lr-case-api
    description: Local API Gateway (https)
paths:
  '/cases':
    get:
      operationId: listCases
      summary: List Cases
      description: Retrieve a filtered list of cases. Supports pagination.
      parameters:
        - name: offset
          in: query
          description: Where to start paging
          required: false
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: The returned case.
          content:
            'application/vnd.logrhythm.case.list.v1+json':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CaseV1'
            'application/vnd.logrhythm.case.list.v2+json':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CaseV2'
  '/cases/{id}':
    put:
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the Case to add evidence to.
          schema:
            type: string
            format: uuid
      operationId: updateCase
      requestBody:
        content:
          'application/vnd.logrhythm.case.v1+json':
            schema:
              $ref: '#/components/schemas/CaseV1'
          'application/vnd.logrhythm.case.v2+json':
            schema:
              $ref: '#/components/schemas/CaseV2'
      responses:
        '200':
          description: The updated cases.
          content:
            'application/vnd.logrhythm.case.list.v1+json':
              schema:
                $ref: '#/components/schemas/CaseV1'
            'application/vnd.logrhythm.case.list.v2+json':
              schema:
                $ref: '#/components/schemas/CaseV2'
  '/cases/{id}/bulk':
    put:
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the Case to add evidence to.
          schema:
            type: string
            format: uuid
      operationId: updateCaseBulk
      requestBody:
        content:
          'application/vnd.logrhythm.case-list.v1+json':
            schema:
              type: array
              items:
                $ref: '#/components/schemas/CaseV1'
          'application/vnd.logrhythm.case-list.v2+json':
            schema:
              type: array
              items:
                $ref: '#/components/schemas/CaseV2'
          'application/vnd.logrhythm.case.list.v3+json':
            schema:
              type: array
              items:
                type: object
                properties:
                  name:
                    type: string
          'application/vnd.logrhythm.case.list.v4+json':
            schema:
              type: object
              properties:
                name:
                  type: string
          'application/vnd.logrhythm.case.list.v5+json':
            schema:
              type: string
      responses:
        '200':
          description: The updated cases.
          content:
            'application/vnd.logrhythm.case.list.v1+json':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CaseV1'
            'application/vnd.logrhythm.case.list.v2+json':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CaseV2'

components:
  schemas:
    CaseV1:
      type: object
      required:
        - id
        - name
        - createdBy
        - lastUpdatedBy
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        name:
          type: string
        createdBy:
          $ref: '#/components/schemas/Person'
        lastUpdatedBy:
          $ref: '#/components/schemas/Person'
    CaseV2:
      type: object
      allOf:
        - $ref: '#/components/schemas/CaseV1'
        - type: object
          required:
            - status
          properties:
            status:
              type: integer
              format: int32
              minimum: 1
              maximum: 5
    Person:
      type: object
      required:
        - id
        - name
      readOnly: true
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
  responses:
    UpdatedCaseAllVersions:
      description: The updated case.
      content:
        'application/vnd.logrhythm.case.list.v1+json':
          schema:
            $ref: '#/components/schemas/CaseV1'
        'application/vnd.logrhythm.case.list.v2+json':
          schema:
            $ref: '#/components/schemas/CaseV2'
