openapi: '3.0.0'
info:
  title: LogRhythm Case API
  version: '3.0.0'
  description: This is the API documentation for the LogRhythm Case service.
servers:
  - url: https://localhost:8501/lr-case-api
    description: Local API Gateway (https)
paths:
  '/cases/{id}/evidence':
    post:
      operationId: createEvidence
      summary: Create Evidence
      description: Add a new piece of evidence to a case.
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the Case to add evidence to.
          schema:
            type: string
            format: uuid
      requestBody:
        content:
          'application/vnd.logrhythm.case-evidence.list.v1+json':
            schema:
              type: object
              oneOf:
                - $ref: '#/components/schemas/NoteEvidence'
                - $ref: '#/components/schemas/AlarmEvidence'
              discriminator:
                propertyName: evidenceType
      responses:
        '201':
          description: The created evidence
          content:
            'application/vnd.logrhythm.case-evidence.list.v1+json':
              schema:
                type: object
                oneOf:
                  - $ref: '#/components/schemas/NoteEvidence'
                  - $ref: '#/components/schemas/AlarmEvidence'
                discriminator:
                  propertyName: evidenceType

components:
  schemas:
    Evidence:
      type: object
      discriminator:
        propertyName: evidenceType
      required:
        - id
        - evidenceType
      properties:
        id:
          type: integer
          format: int32
        evidenceType:
          type: string
        createdBy:
          $ref: '#/components/schemas/Person'
    NoteEvidence:
      type: object
      allOf:
        - $ref: '#/components/schemas/Evidence'
        - type: object
          required:
            - note
          properties:
            note:
              type: string
    AlarmEvidence:
      type: object
      allOf:
        - $ref: '#/components/schemas/Evidence'
        - type: object
          required:
            - alarmId
          properties:
            alarmId:
              type: integer
              format: int32
    Person:
      type: object
      required:
        - id
        - name
      readOnly: true
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
