openapi: '3.0.0'
info:
  title: Request Showcase
  version: '1.0.0'
  description: Demonstrates various types of request bodies
paths:
  '/items':
    get:
      operationId: getItem
      responses:
        '200':
          description: ok
  '/items':
    post:
      operationId: createItems
      requestBody:
        content:
          'application/vnd.Item+json':
            schema:
              $ref: '#/components/schemas/Item'
          'application/vnd.InlineItem+json':
            schema:
              type: object
              properties:
                name:
                  type: string
          'application/vnd.Items+json':
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Item'
          'application/vnd.InlineItems+json':
            schema:
              type: array
              items:
                type: object
                properties:
                  name:
                    type: string
          'application/vnd.ItemsRef+json':
            schema:
              $ref: '#/components/schemas/ItemsRef'
          'application/vnd.NestedItems+json':
            schema:
              $ref: '#/components/schemas/NestedItems'
          'application/vnd.NestedArray+json':
            schema:
              $ref: '#/components/schemas/NestedArray'
          'application/vnd.InlineNestedArray+json':
            schema:
              type: array
              items:
                type: array
                items:
                  type: array
                  items:
                    type: object
                    required:
                      - name
                    properties:
                      name:
                        type: string
          'application/vnd.InlineNestedRef+json':
            schema:
              type: array
              items:
                type: array
                items:
                  $ref: '#/components/schemas/Item'
          'application/vnd.InlineNestedArrayPrimitive+json':
            schema:
              type: array
              items:
                type: array
                items:
                  type: string
          'application/vnd.InlineNestedObject+json':
            schema:
              type: object
              properties:
                nested:
                  type: object
                  properties:
                    nested:
                      type: object
                      required:
                        - name
                      properties:
                        name:
                          type: string
      responses:
        '200':
          description: ok
components:
  schemas:
    Item:
      type: object
      required:
        - name
      properties:
        name:
          type: string
    NestedItems:
      type: array
      items:
        type: object
        required:
          - name
        properties:
          name:
            type: string
    ItemsRef:
      type: array
      items:
        $ref: '#/components/schemas/Item'
    ItemWithRef:
      type: object
      properties:
        nested:
          $ref: '#/components/schemas/Item'
    NestedArray:
      type: array
      items:
        type: array
        items:
          type: object
          required:
            - name
          properties:
            name:
              type: string
